# Generated by Django 4.0 on 2021-12-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название фильма'),
        ),
    ]
