# Generated by Django 4.0 on 2021-12-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0002_film_year_alter_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='actors', to='base_of_films.FilmActor', verbose_name='Актер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='directors', to='base_of_films.FilmDirector', verbose_name='Режиссер'),
        ),
    ]
