# Generated by Django 4.0 on 2021-12-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base_of_films', '0003_alter_film_actor_alter_film_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(max_length=1)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_of_films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
