# Generated by Django 4.0 on 2021-12-28 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0004_filmrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1885), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='filmrating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
