# Generated by Django 4.0 on 2021-12-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0005_alter_film_year_alter_filmrating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdb_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
