# Generated by Django 4.0 on 2021-12-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
    ]
