# Generated by Django 4.0 on 2021-12-29 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0008_rename_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmrating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст рецензии'),
        ),
    ]
