# Generated by Django 4.0 on 2021-12-29 08:41

import base_of_films.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0009_alter_filmrating_score_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(default=None, null=True, upload_to=base_of_films.models.film_directory_path, verbose_name='Изображение'),
        ),
    ]
