# Generated by Django 4.0 on 2021-12-30 11:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0010_film_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('actor', models.BooleanField(default=False)),
                ('director', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.RemoveField(
            model_name='film',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_of_films.filmgenre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1885)]),
        ),
        migrations.DeleteModel(
            name='FilmActor',
        ),
        migrations.DeleteModel(
            name='FilmDirector',
        ),
        migrations.AddField(
            model_name='film',
            name='participants',
            field=models.ManyToManyField(to='base_of_films.FilmParticipant', verbose_name='участник съемок'),
        ),
    ]
