# Generated by Django 4.0 on 2021-12-30 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_of_films', '0011_filmparticipant_remove_film_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='imdb_code',
        ),
        migrations.AddField(
            model_name='film',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
